"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const posts_ctrl_1 = require("./controllers/posts.ctrl");
const users_ctrl_1 = require("./controllers/users.ctrl");
const categories_ctrl_1 = require("./controllers/categories.ctrl");
const contactforms_ctrl_1 = require("./controllers/contactforms.ctrl");
const donations_ctrl_1 = require("./controllers/donations.ctrl");
let router = express.Router();
router.use('/posts', posts_ctrl_1.default);
router.use('/users', users_ctrl_1.default);
router.use('/categories', categories_ctrl_1.default);
router.use('/contactforms', contactforms_ctrl_1.default);
router.use('/donations', donations_ctrl_1.default);
exports.default = router;
