"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const path = require("path");
const express = require("express");
const bodyParser = require("body-parser");
const api_1 = require("./api");
const routing = require("./middleware/routing.mw");
const cookieParser = require("cookie-parser");
const passport_1 = require("./config/passport");
const prerender = require('prerender-node');
prerender.set('prerenderToken', process.env.PRERENDER_TOKEN);
prerender.set('prerenderSerciveUrl', 'http://localhost:1337/');
let clientPath = path.join(__dirname, '../client');
let app = express();
passport_1.default(app);
app.use(express.static(clientPath));
app.use(prerender);
app.use(cookieParser());
app.use(bodyParser.json());
app.use('/api', api_1.default);
app.get('*', routing.stateRouting);
app.listen(process.env.PORT || 3000, () => {
    console.log('Running...');
});
